spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;MODE=PostgreSQL
    username: sa
    password: ''

r2dbc:
  migrate:
    dialect: POSTGRESQL
    resources-paths:
      - classpath:/db/migration/*.sql
