name: Run commands on different operating systems
on:
  push:
    branches: [ main ]

jobs:
  test-maven:
    name: Running test with Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: s4u/setup-maven-action@v1.4.0
        with:
          java-version: 11
          maven-version: 3.8.5
      - run: mvn --version
      - run: mvn clean test
